version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependencias backend"
      - npm install
  build:
    commands:
      - echo "Construyendo con SAM"
      - sam build
  post_build:
    commands:
      - echo "Empaquetando SAM"
      - sam package --output-template-file packaged.yaml --s3-bucket codepipeline-us-east-1-0eedfc749c34-4a12-a6b0-8f4ec0284859
